create table Vacancies(
	Id SERIAL PRIMARY KEY,
	VacancyId VARCHAR(255) NOT NULL,
	Area INTEGER REFERENCES areas(Id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	Salary INTEGER REFERENCES salary(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	Experience experience NOT NULL,
	Schedule schedule NOT NULL,
	Employment employment NOT NULL,
	Description VARCHAR(10000) NOT NULL,
	Skills VARCHAR(100)[] NOT NULL,
	Employer INTEGER REFERENCES employers(Id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	DatePublish TIMESTAMP NOT NULL,
	URL VARCHAR(500) NOT NULL
);